name: Ubuntu SSH Server

on:
  workflow_dispatch:

jobs:
  ssh-server:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
